In [1]:
import pandas as pd
import numpy as np
import torch
import sklearn
import matplotlib
import torchinfo, torchmetrics

# Check PyTorch access (should print out a tensor)
print(torch.randn(3, 3))

# Check for GPU (should return True)
print(torch.cuda.is_available())

tensor([[ 0.1600, -1.0526,  0.3384],
        [-1.6178, -0.7193, -0.8037],
        [ 0.3918, -2.1016, -1.9516]])
False


In [8]:
# Scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [7]:
scalar.ndim

0

In [10]:
# Vector
vector = torch.tensor([7, 9])
vector

tensor([7, 9])

In [11]:
vector.ndim

1

In [13]:
# Matrix 
matrix = torch.tensor([[1,2], [3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [14]:
matrix.ndim

2

In [18]:
# Tensor
tensor_1 = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
tensor_1

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [19]:
tensor_1.ndim

3